insert into case_intake_option_lists (category, label, sort_order) values
  ('onset_cause', '外傷', 1),
  ('onset_cause', '燒傷', 2),
  ('onset_cause', '手術切口', 3),
  ('onset_cause', '疫苗接種', 4),
  ('onset_cause', '痤瘡', 5),
  ('onset_cause', '其他', 99),
  ('referral_source', '家人/朋友介紹', 1),
  ('referral_source', '網路搜尋', 2),
  ('referral_source', '網路平台（IG/FB/Decard等）', 3),
  ('referral_source', '蟹友介紹', 4),
  ('diet_education', '辛辣飲食限制', 1),
  ('diet_education', '海鮮飲食限制', 2),
  ('diet_education', '醬油/深色調味限制', 3),
  ('diet_education', '糯米類限制', 4),
  ('diet_education', '均衡飲食衛教（示範，待部長確認實際項目）', 99),
  ('exercise_restriction', '劇烈運動限制', 1),
  ('exercise_restriction', '傷口部位牽拉/伸展限制', 2),
  ('exercise_restriction', '游泳/泡水限制', 3),
  ('exercise_restriction', '日曬限制', 4),
  ('exercise_restriction', '其他運動禁忌（示範，待部長確認實際項目）', 99)
on conflict do nothing;
